[2020-07-02 14:02:48,255] INFO Watching for file changes with StatReloader
[2020-07-02 14:03:13,865] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:03:14,120] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:03:14,121] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:03:14,993] WARNING "GET /static/favicon-32x32.png HTTP/1.1" 404 179
[2020-07-02 14:03:59,624] INFO Watching for file changes with StatReloader
[2020-07-02 14:04:04,403] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:04:04,453] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:04:04,454] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:04:06,152] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:04:06,222] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:04:06,222] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:04:06,349] WARNING "GET /static/favicon-32x32.png HTTP/1.1" 404 179
[2020-07-02 14:04:06,942] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:04:06,997] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:04:06,997] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:04:07,091] WARNING "GET /static/favicon-32x32.png HTTP/1.1" 404 179
[2020-07-02 14:04:09,873] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:04:09,874] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:04:17,305] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:04:17,586] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:04:17,589] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:04:18,288] WARNING "GET /static/favicon-32x32.png HTTP/1.1" 404 179
[2020-07-02 14:04:36,825] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:04:36,935] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:04:36,973] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:04:37,340] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:04:39,018] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:04:39,138] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:04:39,148] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:04:39,286] WARNING "GET /static/favicon-32x32.png HTTP/1.1" 404 179
[2020-07-02 14:04:40,591] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:04:40,593] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:04:42,603] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:04:42,678] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:04:42,681] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:05:09,093] INFO "POST / HTTP/1.1" 200 1991
[2020-07-02 14:05:09,155] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:05:09,158] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:09:20,066] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:09:20,515] WARNING "GET /favicon.ico HTTP/1.1" 404 179
[2020-07-02 14:09:40,175] INFO "POST / HTTP/1.1" 200 1991
[2020-07-02 14:09:40,249] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:09:40,253] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:10:50,037] INFO "GET /index/ HTTP/1.1" 302 0
[2020-07-02 14:10:50,081] INFO "GET /accounts/login/?next=/index/ HTTP/1.1" 200 1912
[2020-07-02 14:10:50,280] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:10:50,282] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:11:10,235] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:11:10,337] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:11:10,338] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:11:10,553] WARNING "GET /static/favicon-32x32.png HTTP/1.1" 404 179
[2020-07-02 14:12:46,544] INFO Watching for file changes with StatReloader
[2020-07-02 14:13:01,669] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:13:01,751] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:13:01,753] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:13:06,968] INFO "POST / HTTP/1.1" 302 0
[2020-07-02 14:13:07,054] ERROR Internal Server Error: /index/
Traceback (most recent call last):
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: misclientes_enterprise

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dennisqc/WebApps/django-misclientes/misclientes/views.py", line 60, in index
    ultimo_no_contrato = Enterprise.objects.all().aggregate(Max('contract'))
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 384, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 503, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
    cursor.execute(sql, params)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: misclientes_enterprise
[2020-07-02 14:13:07,519] ERROR "GET /index/ HTTP/1.1" 500 145
[2020-07-02 14:13:07,808] WARNING "GET /favicon.ico HTTP/1.1" 404 179
[2020-07-02 14:13:44,272] INFO Watching for file changes with StatReloader
[2020-07-02 14:13:47,818] INFO "GET /index/ HTTP/1.1" 200 7027
[2020-07-02 14:13:47,900] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:13:47,904] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:13:47,913] WARNING "GET /static/js/pace.min.js HTTP/1.1" 404 179
[2020-07-02 14:13:47,922] WARNING "GET /static/css/extra.css HTTP/1.1" 404 179
[2020-07-02 14:13:47,941] WARNING "GET /static/js/jquery-2.2.2.min.js HTTP/1.1" 404 179
[2020-07-02 14:13:47,941] WARNING "GET /static/js/materialize.min.js HTTP/1.1" 404 179
[2020-07-02 14:13:47,945] WARNING "GET /static/js/clientes.js HTTP/1.1" 404 179
[2020-07-02 14:15:11,077] INFO "GET /index/ HTTP/1.1" 200 7027
[2020-07-02 14:15:11,170] WARNING "GET /static/js/clientes.js HTTP/1.1" 404 179
[2020-07-02 14:15:11,170] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:15:11,171] WARNING "GET /static/js/materialize.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:11,171] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:15:11,171] WARNING "GET /static/js/jquery-2.2.2.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:11,171] WARNING "GET /static/css/extra.css HTTP/1.1" 404 179
[2020-07-02 14:15:11,199] WARNING "GET /static/js/pace.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:14,983] INFO "GET /index/ HTTP/1.1" 200 7027
[2020-07-02 14:15:15,070] WARNING "GET /static/js/clientes.js HTTP/1.1" 404 179
[2020-07-02 14:15:15,071] WARNING "GET /static/js/jquery-2.2.2.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:15,075] WARNING "GET /static/css/extra.css HTTP/1.1" 404 179
[2020-07-02 14:15:15,075] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:15:15,076] WARNING "GET /static/js/materialize.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:15,076] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:15:15,099] WARNING "GET /static/js/pace.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:15,289] WARNING "GET /static/favicon-32x32.png HTTP/1.1" 404 179
[2020-07-02 14:15:30,682] INFO Watching for file changes with StatReloader
[2020-07-02 14:15:35,004] INFO "GET /index/ HTTP/1.1" 200 7004
[2020-07-02 14:15:35,089] WARNING "GET /static/css/extra.css HTTP/1.1" 404 179
[2020-07-02 14:15:35,091] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:15:35,091] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:15:35,093] WARNING "GET /static/js/jquery-2.2.2.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:35,099] WARNING "GET /static/js/pace.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:35,102] WARNING "GET /static/js/materialize.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:35,120] WARNING "GET /static/js/clientes.js HTTP/1.1" 404 179
[2020-07-02 14:15:36,654] INFO "GET /expirados/ HTTP/1.1" 200 3263
[2020-07-02 14:15:36,776] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:15:36,792] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:15:36,800] WARNING "GET /static/css/extra.css HTTP/1.1" 404 179
[2020-07-02 14:15:36,804] WARNING "GET /static/js/jquery-2.2.2.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:36,807] WARNING "GET /static/js/materialize.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:36,824] WARNING "GET /static/js/pace.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:36,827] WARNING "GET /static/js/clientes.js HTTP/1.1" 404 179
[2020-07-02 14:15:42,112] INFO "GET /index/ HTTP/1.1" 200 7004
[2020-07-02 14:15:42,204] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:15:42,209] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:15:42,217] WARNING "GET /static/css/extra.css HTTP/1.1" 404 179
[2020-07-02 14:15:42,233] WARNING "GET /static/js/jquery-2.2.2.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:42,235] WARNING "GET /static/js/materialize.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:42,244] WARNING "GET /static/js/clientes.js HTTP/1.1" 404 179
[2020-07-02 14:15:42,245] WARNING "GET /static/js/pace.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:43,180] INFO "GET /clientes/ HTTP/1.1" 200 3768
[2020-07-02 14:15:43,283] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:15:43,345] WARNING "GET /static/js/clientes.js HTTP/1.1" 404 179
[2020-07-02 14:15:43,353] WARNING "GET /static/js/pace.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:43,353] WARNING "GET /static/css/extra.css HTTP/1.1" 404 179
[2020-07-02 14:15:43,354] WARNING "GET /static/js/jquery-2.2.2.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:43,355] WARNING "GET /static/js/materialize.min.js HTTP/1.1" 404 179
[2020-07-02 14:15:43,361] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:17:43,617] INFO "GET /addclientes HTTP/1.1" 301 0
[2020-07-02 14:17:43,915] INFO "GET /addclientes/ HTTP/1.1" 200 10493
[2020-07-02 14:17:44,018] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:17:44,019] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:17:44,023] WARNING "GET /static/js/clientes.js HTTP/1.1" 404 179
[2020-07-02 14:17:44,031] WARNING "GET /static/js/materialize.min.js HTTP/1.1" 404 179
[2020-07-02 14:17:44,038] WARNING "GET /static/js/jquery-2.2.2.min.js HTTP/1.1" 404 179
[2020-07-02 14:17:44,040] WARNING "GET /static/css/extra.css HTTP/1.1" 404 179
[2020-07-02 14:17:44,044] WARNING "GET /static/js/pace.min.js HTTP/1.1" 404 179
[2020-07-02 14:18:07,725] INFO "GET /accounts/logout/ HTTP/1.1" 302 0
[2020-07-02 14:18:07,793] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:18:07,863] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:18:07,872] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:22:30,884] INFO Watching for file changes with StatReloader
[2020-07-02 14:22:39,034] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:22:39,070] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:22:39,070] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:22:39,299] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:22:39,597] WARNING "GET /static/favicon-32x32.png HTTP/1.1" 404 179
[2020-07-02 14:24:00,685] INFO /home/dennisqc/WebApps/django-misclientes/clients/settings.py changed, reloading.
[2020-07-02 14:24:05,058] INFO Watching for file changes with StatReloader
[2020-07-02 14:24:11,075] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:24:11,132] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:24:11,133] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:24:11,917] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:24:12,017] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:24:12,017] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:24:20,700] INFO /home/dennisqc/WebApps/django-misclientes/clients/settings.py changed, reloading.
[2020-07-02 14:24:21,123] INFO Watching for file changes with StatReloader
[2020-07-02 14:24:24,381] INFO /home/dennisqc/WebApps/django-misclientes/clients/settings.py changed, reloading.
[2020-07-02 14:24:24,777] INFO Watching for file changes with StatReloader
[2020-07-02 14:24:27,568] INFO /home/dennisqc/WebApps/django-misclientes/clients/settings.py changed, reloading.
[2020-07-02 14:24:28,003] INFO Watching for file changes with StatReloader
[2020-07-02 14:24:34,331] ERROR Internal Server Error: /
Traceback (most recent call last):
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 501, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 33, in __init__
    check_settings(base_url)
  File "/home/dennisqc/WebApps/django-misclientes/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/utils.py", line 49, in check_settings
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the required STATIC_URL setting.
[2020-07-02 14:24:34,545] ERROR "GET / HTTP/1.1" 500 145
[2020-07-02 14:24:34,866] WARNING "GET /favicon.ico HTTP/1.1" 404 179
[2020-07-02 14:24:51,370] INFO /home/dennisqc/WebApps/django-misclientes/clients/settings.py changed, reloading.
[2020-07-02 14:24:51,882] INFO Watching for file changes with StatReloader
[2020-07-02 14:24:55,334] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:24:55,394] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:24:55,396] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:24:56,345] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:24:56,404] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:24:56,404] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:24:56,966] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:24:57,031] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:24:57,033] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:24:57,211] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:24:57,298] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:24:57,330] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-07-02 14:24:58,138] INFO "GET / HTTP/1.1" 200 1768
[2020-07-02 14:24:58,212] WARNING "GET /static/css/materialize.min.css HTTP/1.1" 404 179
[2020-07-02 14:24:58,212] WARNING "GET /static/css/google_material_icons.css HTTP/1.1" 404 179
[2020-08-03 16:37:43,919] INFO Watching for file changes with StatReloader
[2020-08-03 16:38:13,665] INFO Watching for file changes with StatReloader
[2020-08-03 16:38:22,301] INFO "GET / HTTP/1.1" 200 1768
[2020-08-03 16:38:22,435] INFO "GET /static/css/google_material_icons.css HTTP/1.1" 200 859
[2020-08-03 16:38:22,436] INFO "GET /static/css/materialize.min.css HTTP/1.1" 200 141841
[2020-08-03 16:38:22,924] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 16:38:40,463] INFO "POST / HTTP/1.1" 302 0
[2020-08-03 16:39:26,716] INFO "GET / HTTP/1.1" 200 1768
[2020-08-03 16:39:27,088] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 16:39:30,869] INFO "GET /index HTTP/1.1" 301 0
[2020-08-03 16:39:30,983] INFO "GET /index/ HTTP/1.1" 200 7004
[2020-08-03 16:39:31,056] INFO "GET /static/css/extra.css HTTP/1.1" 200 317
[2020-08-03 16:39:31,063] INFO "GET /static/js/jquery-2.2.2.min.js HTTP/1.1" 200 85656
[2020-08-03 16:39:31,068] INFO "GET /static/js/pace.min.js HTTP/1.1" 200 12363
[2020-08-03 16:39:31,082] INFO "GET /static/js/materialize.min.js HTTP/1.1" 200 181109
[2020-08-03 16:39:31,085] INFO "GET /static/js/clientes.js HTTP/1.1" 200 2182
[2020-08-03 16:39:31,298] INFO "GET /static/fonts/google_material_icons.woff2 HTTP/1.1" 200 55208
[2020-08-03 16:39:42,744] INFO "GET /expirados/ HTTP/1.1" 200 3263
[2020-08-03 16:39:45,173] INFO "GET /expirados/ HTTP/1.1" 200 3263
[2020-08-03 16:39:47,174] INFO "GET /addclientes HTTP/1.1" 301 0
[2020-08-03 16:39:47,454] INFO "GET /addclientes/ HTTP/1.1" 200 10493
[2020-08-03 16:43:25,088] INFO Watching for file changes with StatReloader
[2020-08-03 16:43:36,768] WARNING Session data corrupted
[2020-08-03 16:43:36,849] INFO "GET /addclientes/ HTTP/1.1" 302 0
[2020-08-03 16:43:37,288] WARNING Session data corrupted
[2020-08-03 16:43:37,498] INFO "GET /accounts/login/?next=/addclientes/ HTTP/1.1" 200 1918
[2020-08-03 16:43:42,972] WARNING Session data corrupted
[2020-08-03 16:43:43,388] INFO "POST / HTTP/1.1" 302 0
[2020-08-03 16:43:43,563] INFO "GET /addclientes/ HTTP/1.1" 200 10141
[2020-08-03 16:43:50,217] INFO "GET /admin/ HTTP/1.1" 200 5910
[2020-08-03 16:43:50,597] INFO "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[2020-08-03 16:43:50,610] INFO "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[2020-08-03 16:43:50,713] INFO "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2020-08-03 16:43:50,777] INFO "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2020-08-03 16:43:50,940] INFO "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[2020-08-03 16:44:49,215] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/admin.py changed, reloading.
[2020-08-03 16:44:49,713] INFO Watching for file changes with StatReloader
[2020-08-03 16:45:05,451] INFO "GET /admin/logout/ HTTP/1.1" 302 0
[2020-08-03 16:45:05,514] INFO "GET / HTTP/1.1" 200 1768
[2020-08-03 16:45:09,630] INFO "POST / HTTP/1.1" 302 0
[2020-08-03 16:45:09,683] INFO "GET /index/ HTTP/1.1" 200 7004
[2020-08-03 16:45:11,641] INFO "GET /addclientes/ HTTP/1.1" 200 10141
[2020-08-03 16:45:38,511] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/forms.py changed, reloading.
[2020-08-03 16:45:39,018] INFO Watching for file changes with StatReloader
[2020-08-03 16:45:41,585] INFO "GET /addclientes/ HTTP/1.1" 200 10522
[2020-08-03 16:45:41,972] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 16:48:40,671] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 16:48:41,226] INFO Watching for file changes with StatReloader
[2020-08-03 16:48:47,573] ERROR Internal Server Error: /printclientlist
Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py", line 265, in printClientList
    html = render_to_string("listapdf.html", {
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 1078, in load
    lib = find_library(parser, name)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 1023, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
[2020-08-03 16:48:47,579] ERROR "GET /printclientlist HTTP/1.1" 500 147509
[2020-08-03 16:49:48,285] INFO "GET /printclientlist HTTP/1.1" 200 17428
[2020-08-03 16:50:29,612] INFO "GET /clientes/ HTTP/1.1" 302 0
[2020-08-03 16:50:29,654] INFO "GET /accounts/login/?next=/clientes/ HTTP/1.1" 200 1915
[2020-08-03 16:50:33,755] INFO "POST / HTTP/1.1" 302 0
[2020-08-03 16:50:33,795] INFO "GET /clientes/ HTTP/1.1" 200 20816
[2020-08-03 16:50:39,114] INFO "GET /printclientlist HTTP/1.1" 200 86728
[2020-08-03 16:52:28,801] INFO "GET /printclientlist HTTP/1.1" 200 86729
[2020-08-03 16:53:20,315] INFO "GET /printclientlist HTTP/1.1" 200 86730
[2020-08-03 16:53:58,138] INFO "GET /clientes/ HTTP/1.1" 200 20816
[2020-08-03 16:53:58,490] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 16:54:56,334] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 16:54:56,808] INFO Watching for file changes with StatReloader
[2020-08-03 16:55:11,617] INFO Watching for file changes with StatReloader
[2020-08-03 16:55:40,751] INFO "GET /clientes/ HTTP/1.1" 200 20816
[2020-08-03 16:55:41,106] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 16:55:43,236] ERROR Internal Server Error: /printclientlist
Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 1021, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py", line 265, in printClientList
    html = render_to_string("listapdf.html", {
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 1078, in load
    lib = find_library(parser, name)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 1023, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
[2020-08-03 16:55:43,239] ERROR "GET /printclientlist HTTP/1.1" 500 149977
[2020-08-03 16:55:53,986] INFO "GET /printclientlist HTTP/1.1" 200 88419
[2020-08-03 16:57:54,122] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 16:57:54,676] INFO Watching for file changes with StatReloader
[2020-08-03 16:58:01,775] INFO "GET /printclientlist HTTP/1.1" 200 88289
[2020-08-03 17:00:05,068] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:00:05,554] INFO Watching for file changes with StatReloader
[2020-08-03 17:00:13,446] INFO "GET /printclientlist HTTP/1.1" 200 88290
[2020-08-03 17:00:41,971] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:00:42,497] INFO Watching for file changes with StatReloader
[2020-08-03 17:00:46,605] INFO "GET /clientdetail/131/ HTTP/1.1" 200 6940
[2020-08-03 17:00:46,686] INFO "GET /static/pesca.jpg HTTP/1.1" 200 37683
[2020-08-03 17:00:49,221] INFO "GET /printreport/131 HTTP/1.1" 200 23467
[2020-08-03 17:01:33,954] INFO "GET /addclientes/ HTTP/1.1" 200 10745
[2020-08-03 17:01:34,701] INFO "GET /expirados/ HTTP/1.1" 200 8997
[2020-08-03 17:01:44,522] INFO "GET /addclientes/ HTTP/1.1" 200 10745
[2020-08-03 17:03:41,003] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/models.py changed, reloading.
[2020-08-03 17:03:41,452] INFO Watching for file changes with StatReloader
[2020-08-03 17:03:51,724] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/models.py changed, reloading.
[2020-08-03 17:03:52,214] INFO Watching for file changes with StatReloader
[2020-08-03 17:05:11,765] INFO Watching for file changes with StatReloader
[2020-08-03 17:05:15,252] INFO "GET /addclientes/ HTTP/1.1" 200 10534
[2020-08-03 17:05:15,596] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 17:05:21,825] INFO "GET /admin/ HTTP/1.1" 200 8588
[2020-08-03 17:05:22,085] INFO "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[2020-08-03 17:05:51,603] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/admin.py changed, reloading.
[2020-08-03 17:05:52,104] INFO Watching for file changes with StatReloader
[2020-08-03 17:05:54,171] INFO "GET /admin/ HTTP/1.1" 200 9093
[2020-08-03 17:05:55,660] INFO "GET /admin/misclientes/type_of_contract/ HTTP/1.1" 200 3321
[2020-08-03 17:05:55,764] INFO "GET /static/admin/css/changelists.css HTTP/1.1" 200 6190
[2020-08-03 17:05:55,783] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[2020-08-03 17:05:55,787] INFO "GET /static/admin/js/core.js HTTP/1.1" 200 5723
[2020-08-03 17:05:55,789] INFO "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
[2020-08-03 17:05:55,807] INFO "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
[2020-08-03 17:05:55,807] INFO "GET /static/admin/js/urlify.js HTTP/1.1" 200 8941
[2020-08-03 17:05:55,808] INFO "GET /static/admin/js/actions.js HTTP/1.1" 200 6766
[2020-08-03 17:05:55,808] INFO "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
[2020-08-03 17:05:55,815] INFO "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
[2020-08-03 17:05:55,824] INFO "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
[2020-08-03 17:05:55,932] INFO "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[2020-08-03 17:05:56,990] INFO "GET /admin/misclientes/type_of_contract/add/ HTTP/1.1" 200 4161
[2020-08-03 17:05:57,066] INFO "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
[2020-08-03 17:05:57,067] INFO "GET /static/admin/css/forms.css HTTP/1.1" 200 8518
[2020-08-03 17:05:57,067] INFO "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
[2020-08-03 17:05:57,076] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[2020-08-03 17:05:57,124] INFO "GET /static/admin/css/widgets.css HTTP/1.1" 200 10322
[2020-08-03 17:05:59,742] INFO "POST /admin/misclientes/type_of_contract/add/ HTTP/1.1" 302 0
[2020-08-03 17:05:59,864] INFO "GET /admin/misclientes/type_of_contract/ HTTP/1.1" 200 4760
[2020-08-03 17:05:59,937] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[2020-08-03 17:06:00,022] INFO "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[2020-08-03 17:06:01,426] INFO "GET /admin/misclientes/type_of_contract/add/ HTTP/1.1" 200 4161
[2020-08-03 17:06:01,506] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[2020-08-03 17:06:04,372] INFO "POST /admin/misclientes/type_of_contract/add/ HTTP/1.1" 302 0
[2020-08-03 17:06:04,483] INFO "GET /admin/misclientes/type_of_contract/ HTTP/1.1" 200 5009
[2020-08-03 17:06:04,557] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[2020-08-03 17:06:05,531] INFO "GET /admin/misclientes/type_of_contract/add/ HTTP/1.1" 200 4161
[2020-08-03 17:06:05,605] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[2020-08-03 17:06:09,006] INFO "POST /admin/misclientes/type_of_contract/add/ HTTP/1.1" 302 0
[2020-08-03 17:06:09,139] INFO "GET /admin/misclientes/type_of_contract/ HTTP/1.1" 200 5252
[2020-08-03 17:06:09,210] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 7069
[2020-08-03 17:06:16,355] INFO "GET / HTTP/1.1" 200 1768
[2020-08-03 17:06:20,282] INFO "POST / HTTP/1.1" 302 0
[2020-08-03 17:06:20,374] INFO "GET /index/ HTTP/1.1" 200 7009
[2020-08-03 17:06:21,990] INFO "GET /addclientes/ HTTP/1.1" 200 10667
[2020-08-03 17:06:44,849] INFO "POST /addpersonas/ HTTP/1.1" 200 40
[2020-08-03 17:06:46,754] INFO "GET /addclientes/ HTTP/1.1" 200 10732
[2020-08-03 17:07:05,995] ERROR Internal Server Error: /addclientes/
Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py", line 101, in addempresa
    nuevaempresa = empresa.save()
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/forms/models.py", line 459, in save
    self.instance.save()
  File "/home/dcruz/WebApps/Github/django-misclientes/misclientes/models.py", line 118, in save
    self.expire_on = self.signed + timedelta(days=365)
NameError: name 'timedelta' is not defined
[2020-08-03 17:07:05,999] ERROR "POST /addclientes/ HTTP/1.1" 500 96381
[2020-08-03 17:07:45,688] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/models.py changed, reloading.
[2020-08-03 17:07:46,271] INFO Watching for file changes with StatReloader
[2020-08-03 17:07:50,504] INFO "POST /addclientes/ HTTP/1.1" 302 0
[2020-08-03 17:07:50,616] INFO "GET /index/ HTTP/1.1" 200 7009
[2020-08-03 17:07:53,197] INFO "GET /clientes/ HTTP/1.1" 200 21000
[2020-08-03 17:07:57,994] INFO "GET /clientes/?page=14 HTTP/1.1" 200 14087
[2020-08-03 17:08:00,410] INFO "GET /clientdetail/142/ HTTP/1.1" 200 6014
[2020-08-03 17:08:58,573] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:08:59,007] INFO Watching for file changes with StatReloader
[2020-08-03 17:09:45,099] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:09:45,533] INFO Watching for file changes with StatReloader
[2020-08-03 17:10:14,146] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:10:14,656] INFO Watching for file changes with StatReloader
[2020-08-03 17:11:10,762] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:11:11,194] INFO Watching for file changes with StatReloader
[2020-08-03 17:12:44,388] ERROR Internal Server Error: /clientdetail/142/
Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py", line 184, in get_context_data
    contract = Type_of_Contract.objects.get(pk=self.kwargs['pk'])
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(
misclientes.models.Type_of_Contract.DoesNotExist: Type_of_Contract matching query does not exist.
[2020-08-03 17:12:44,392] ERROR "GET /clientdetail/142/ HTTP/1.1" 500 108017
[2020-08-03 17:15:03,693] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/models.py changed, reloading.
[2020-08-03 17:15:04,207] INFO Watching for file changes with StatReloader
[2020-08-03 17:15:20,136] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:15:20,597] INFO Watching for file changes with StatReloader
[2020-08-03 17:15:31,875] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:15:32,299] INFO Watching for file changes with StatReloader
[2020-08-03 17:15:51,577] INFO Watching for file changes with StatReloader
[2020-08-03 17:16:25,691] ERROR Internal Server Error: /clientdetail/142/
Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py", line 184, in get_context_data
    contract = Type_of_Contract.objects.get(pk=self.kwargs['pk'])
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(
misclientes.models.Type_of_Contract.DoesNotExist: Type_of_Contract matching query does not exist.
[2020-08-03 17:16:25,694] ERROR "GET /clientdetail/142/ HTTP/1.1" 500 108039
[2020-08-03 17:16:45,072] INFO "GET /addclientes/ HTTP/1.1" 200 10667
[2020-08-03 17:16:51,344] INFO "GET /clientes/ HTTP/1.1" 200 21000
[2020-08-03 17:17:21,210] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:17:21,637] INFO Watching for file changes with StatReloader
[2020-08-03 17:17:35,798] INFO "GET /clientes/?page=14 HTTP/1.1" 200 14087
[2020-08-03 17:17:37,817] ERROR Internal Server Error: /clientdetail/142/
Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py", line 184, in get_context_data
    contract = Type_of_Contract.objects.get(pk=self.kwargs['pk'])
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(
misclientes.models.Type_of_Contract.DoesNotExist: Type_of_Contract matching query does not exist.
[2020-08-03 17:17:37,819] ERROR "GET /clientdetail/142/ HTTP/1.1" 500 107903
[2020-08-03 17:19:57,077] INFO Watching for file changes with StatReloader
[2020-08-03 17:19:59,787] ERROR Internal Server Error: /clientdetail/142/
Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py", line 184, in get_context_data
    contract = Type_of_Contract.objects.get(pk=self.kwargs['pk'])
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(
misclientes.models.Type_of_Contract.DoesNotExist: Type_of_Contract matching query does not exist.
[2020-08-03 17:19:59,789] ERROR "GET /clientdetail/142/ HTTP/1.1" 500 108039
[2020-08-03 17:21:20,466] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/models.py changed, reloading.
[2020-08-03 17:21:21,034] INFO Watching for file changes with StatReloader
[2020-08-03 17:21:27,095] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:21:27,559] INFO Watching for file changes with StatReloader
[2020-08-03 17:21:30,457] ERROR Internal Server Error: /clientdetail/142/
Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py", line 184, in get_context_data
    contract = Type_of_Contract.objects.get(pk=self.kwargs['pk'])
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/db/models/query.py", line 415, in get
    raise self.model.DoesNotExist(
misclientes.models.Type_of_Contract.DoesNotExist: Type_of_Contract matching query does not exist.
[2020-08-03 17:21:30,458] ERROR "GET /clientdetail/142/ HTTP/1.1" 500 108036
[2020-08-03 17:21:58,727] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:21:59,238] INFO Watching for file changes with StatReloader
[2020-08-03 17:22:01,497] ERROR Internal Server Error: /clientdetail/142/
Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py", line 185, in get_context_data
    context['tipo_de_contrato'] = cliente.tipo_contrato.all()
AttributeError: 'Enterprise' object has no attribute 'tipo_contrato'
[2020-08-03 17:22:01,498] ERROR "GET /clientdetail/142/ HTTP/1.1" 500 99096
[2020-08-03 17:22:14,128] INFO /home/dcruz/WebApps/Github/django-misclientes/misclientes/views.py changed, reloading.
[2020-08-03 17:22:14,785] INFO Watching for file changes with StatReloader
[2020-08-03 17:22:16,805] INFO "GET /clientdetail/142/ HTTP/1.1" 200 6056
[2020-08-03 17:22:37,849] INFO "GET /clientdetail/142/ HTTP/1.1" 200 6120
[2020-08-03 17:22:38,109] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 17:22:50,589] INFO "GET /clientdetail/142/ HTTP/1.1" 200 6096
[2020-08-03 17:22:50,956] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 17:23:35,824] INFO "GET /clientdetail/142/ HTTP/1.1" 200 6188
[2020-08-03 17:23:36,149] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 17:23:46,492] INFO "GET /clientes/ HTTP/1.1" 200 21000
[2020-08-03 17:25:20,764] ERROR Internal Server Error: /clientes/
Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'ManyRelatedManager' object is not iterable
[2020-08-03 17:25:20,765] ERROR "GET /clientes/ HTTP/1.1" 500 202294
[2020-08-03 17:27:33,295] INFO "GET /clientes/ HTTP/1.1" 200 20030
[2020-08-03 17:27:33,679] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 17:27:53,924] INFO "GET /clientes/ HTTP/1.1" 200 20030
[2020-08-03 17:27:54,264] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 17:28:03,959] INFO "GET /clientes/ HTTP/1.1" 200 20030
[2020-08-03 17:28:04,287] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 17:28:06,689] INFO "GET /clientes/?page=14 HTTP/1.1" 200 13505
[2020-08-03 17:28:51,478] ERROR Internal Server Error: /clientes/
Traceback (most recent call last):
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/dcruz/WebApps/environments/misclientesenv/lib64/python3.8/site-packages/django/template/defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'ManyRelatedManager' object is not iterable
[2020-08-03 17:28:51,479] ERROR "GET /clientes/?page=14 HTTP/1.1" 500 193782
[2020-08-03 17:35:01,440] INFO "GET /clientes/?page=14 HTTP/1.1" 200 13842
[2020-08-03 17:35:01,853] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 17:36:02,111] INFO "GET /clientes/?page=14 HTTP/1.1" 200 13842
[2020-08-03 17:36:02,468] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
[2020-08-03 17:36:11,882] INFO "GET /clientdetail/142/ HTTP/1.1" 200 6188
[2020-08-03 17:36:39,110] INFO "GET /clientes/?page=14 HTTP/1.1" 200 13815
[2020-08-03 17:36:39,441] INFO "GET /static/favicon-32x32.png HTTP/1.1" 200 2030
